// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

/**
 * https://github.com/hyperledger/aries-framework-javascript/tree/d895c78e0e02954a95ad1fd7e2251ee9a02445dc/packages/question-answer
 * 
 * Main question data root
 * 
 * Double duties as questionanswerrecord
 * 
 * {
 *   "_tags": {
 *     "connectionId": "4b54a752-467b-4c80-a973-7203177b3bef",
 *     "role": "questioner",
 *     "state": "answer-received",
 *     "threadId": "91e48b89-84a6-4d54-a8d4-21668071322b"
 *   },
 *   "metadata": {},
 *   "id": "4bac7220-af4a-47dd-9dde-26c4a1fde246",
 *   "createdAt": "2023-07-31T11:38:17.981Z",
 *   "questionText": "Do you want to play?",
 *   "validResponses": [
 *     {
 *       "text": "Yes"
 *     },
 *     {
 *       "text": "No"
 *     }
 *   ],
 *   "connectionId": "4b54a752-467b-4c80-a973-7203177b3bef",
 *   "role": "questioner",
 *   "signatureRequired": false,
 *   "state": "answer-received",
 *   "threadId": "91e48b89-84a6-4d54-a8d4-21668071322b",
 *   "updatedAt": "2023-07-31T11:38:19.459Z",
 *   "response": "Yes"
 * }
 * 
 */
public class Survey
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject surveyMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Survey";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		id_("id_"),
		signature_required("signature_required"),
		connectionId("connectionId"),
		role("role"),
		state("state"),
		threadId("threadId"),
		updatedAt("updatedAt"),
		createdAt("createdAt"),
		metadata("metadata"),
		_tags("_tags"),
		survey_id("survey_id"),
		surveyTitle("surveyTitle"),
		surveyDescription("surveyDescription"),
		survey_schema("survey_schema"),
		ui_schema("ui_schema"),
		init_data("init_data"),
		i18n_data("i18n_data"),
		response("response"),
		language("language"),
		readonly("readonly"),
		jsonStyle("jsonStyle");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Survey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Survey(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject surveyMendixObject)
	{
		if (surveyMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, surveyMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.surveyMendixObject = surveyMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Survey.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Survey initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Survey.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Survey initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Survey(context, mendixObject);
	}

	public static myfirstmodule.proxies.Survey load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Survey.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of id_
	 */
	public final java.lang.String getid_()
	{
		return getid_(getContext());
	}

	/**
	 * @param context
	 * @return value of id_
	 */
	public final java.lang.String getid_(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.id_.toString());
	}

	/**
	 * Set value of id_
	 * @param id_
	 */
	public final void setid_(java.lang.String id_)
	{
		setid_(getContext(), id_);
	}

	/**
	 * Set value of id_
	 * @param context
	 * @param id_
	 */
	public final void setid_(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String id_)
	{
		getMendixObject().setValue(context, MemberNames.id_.toString(), id_);
	}

	/**
	 * @return value of signature_required
	 */
	public final java.lang.Boolean getsignature_required()
	{
		return getsignature_required(getContext());
	}

	/**
	 * @param context
	 * @return value of signature_required
	 */
	public final java.lang.Boolean getsignature_required(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.signature_required.toString());
	}

	/**
	 * Set value of signature_required
	 * @param signature_required
	 */
	public final void setsignature_required(java.lang.Boolean signature_required)
	{
		setsignature_required(getContext(), signature_required);
	}

	/**
	 * Set value of signature_required
	 * @param context
	 * @param signature_required
	 */
	public final void setsignature_required(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean signature_required)
	{
		getMendixObject().setValue(context, MemberNames.signature_required.toString(), signature_required);
	}

	/**
	 * @return value of connectionId
	 */
	public final java.lang.String getconnectionId()
	{
		return getconnectionId(getContext());
	}

	/**
	 * @param context
	 * @return value of connectionId
	 */
	public final java.lang.String getconnectionId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.connectionId.toString());
	}

	/**
	 * Set value of connectionId
	 * @param connectionid
	 */
	public final void setconnectionId(java.lang.String connectionid)
	{
		setconnectionId(getContext(), connectionid);
	}

	/**
	 * Set value of connectionId
	 * @param context
	 * @param connectionid
	 */
	public final void setconnectionId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String connectionid)
	{
		getMendixObject().setValue(context, MemberNames.connectionId.toString(), connectionid);
	}

	/**
	 * @return value of role
	 */
	public final java.lang.String getrole()
	{
		return getrole(getContext());
	}

	/**
	 * @param context
	 * @return value of role
	 */
	public final java.lang.String getrole(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.role.toString());
	}

	/**
	 * Set value of role
	 * @param role
	 */
	public final void setrole(java.lang.String role)
	{
		setrole(getContext(), role);
	}

	/**
	 * Set value of role
	 * @param context
	 * @param role
	 */
	public final void setrole(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String role)
	{
		getMendixObject().setValue(context, MemberNames.role.toString(), role);
	}

	/**
	 * @return value of state
	 */
	public final java.lang.String getstate()
	{
		return getstate(getContext());
	}

	/**
	 * @param context
	 * @return value of state
	 */
	public final java.lang.String getstate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.state.toString());
	}

	/**
	 * Set value of state
	 * @param state
	 */
	public final void setstate(java.lang.String state)
	{
		setstate(getContext(), state);
	}

	/**
	 * Set value of state
	 * @param context
	 * @param state
	 */
	public final void setstate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String state)
	{
		getMendixObject().setValue(context, MemberNames.state.toString(), state);
	}

	/**
	 * @return value of threadId
	 */
	public final java.lang.String getthreadId()
	{
		return getthreadId(getContext());
	}

	/**
	 * @param context
	 * @return value of threadId
	 */
	public final java.lang.String getthreadId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.threadId.toString());
	}

	/**
	 * Set value of threadId
	 * @param threadid
	 */
	public final void setthreadId(java.lang.String threadid)
	{
		setthreadId(getContext(), threadid);
	}

	/**
	 * Set value of threadId
	 * @param context
	 * @param threadid
	 */
	public final void setthreadId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String threadid)
	{
		getMendixObject().setValue(context, MemberNames.threadId.toString(), threadid);
	}

	/**
	 * @return value of updatedAt
	 */
	public final java.util.Date getupdatedAt()
	{
		return getupdatedAt(getContext());
	}

	/**
	 * @param context
	 * @return value of updatedAt
	 */
	public final java.util.Date getupdatedAt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.updatedAt.toString());
	}

	/**
	 * Set value of updatedAt
	 * @param updatedat
	 */
	public final void setupdatedAt(java.util.Date updatedat)
	{
		setupdatedAt(getContext(), updatedat);
	}

	/**
	 * Set value of updatedAt
	 * @param context
	 * @param updatedat
	 */
	public final void setupdatedAt(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date updatedat)
	{
		getMendixObject().setValue(context, MemberNames.updatedAt.toString(), updatedat);
	}

	/**
	 * @return value of createdAt
	 */
	public final java.util.Date getcreatedAt()
	{
		return getcreatedAt(getContext());
	}

	/**
	 * @param context
	 * @return value of createdAt
	 */
	public final java.util.Date getcreatedAt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.createdAt.toString());
	}

	/**
	 * Set value of createdAt
	 * @param createdat
	 */
	public final void setcreatedAt(java.util.Date createdat)
	{
		setcreatedAt(getContext(), createdat);
	}

	/**
	 * Set value of createdAt
	 * @param context
	 * @param createdat
	 */
	public final void setcreatedAt(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date createdat)
	{
		getMendixObject().setValue(context, MemberNames.createdAt.toString(), createdat);
	}

	/**
	 * @return value of metadata
	 */
	public final java.lang.String getmetadata()
	{
		return getmetadata(getContext());
	}

	/**
	 * @param context
	 * @return value of metadata
	 */
	public final java.lang.String getmetadata(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.metadata.toString());
	}

	/**
	 * Set value of metadata
	 * @param metadata
	 */
	public final void setmetadata(java.lang.String metadata)
	{
		setmetadata(getContext(), metadata);
	}

	/**
	 * Set value of metadata
	 * @param context
	 * @param metadata
	 */
	public final void setmetadata(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String metadata)
	{
		getMendixObject().setValue(context, MemberNames.metadata.toString(), metadata);
	}

	/**
	 * @return value of _tags
	 */
	public final java.lang.String get_tags()
	{
		return get_tags(getContext());
	}

	/**
	 * @param context
	 * @return value of _tags
	 */
	public final java.lang.String get_tags(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._tags.toString());
	}

	/**
	 * Set value of _tags
	 * @param _tags
	 */
	public final void set_tags(java.lang.String _tags)
	{
		set_tags(getContext(), _tags);
	}

	/**
	 * Set value of _tags
	 * @param context
	 * @param _tags
	 */
	public final void set_tags(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _tags)
	{
		getMendixObject().setValue(context, MemberNames._tags.toString(), _tags);
	}

	/**
	 * @return value of survey_id
	 */
	public final java.lang.String getsurvey_id()
	{
		return getsurvey_id(getContext());
	}

	/**
	 * @param context
	 * @return value of survey_id
	 */
	public final java.lang.String getsurvey_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.survey_id.toString());
	}

	/**
	 * Set value of survey_id
	 * @param survey_id
	 */
	public final void setsurvey_id(java.lang.String survey_id)
	{
		setsurvey_id(getContext(), survey_id);
	}

	/**
	 * Set value of survey_id
	 * @param context
	 * @param survey_id
	 */
	public final void setsurvey_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String survey_id)
	{
		getMendixObject().setValue(context, MemberNames.survey_id.toString(), survey_id);
	}

	/**
	 * @return value of surveyTitle
	 */
	public final java.lang.String getsurveyTitle()
	{
		return getsurveyTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of surveyTitle
	 */
	public final java.lang.String getsurveyTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.surveyTitle.toString());
	}

	/**
	 * Set value of surveyTitle
	 * @param surveytitle
	 */
	public final void setsurveyTitle(java.lang.String surveytitle)
	{
		setsurveyTitle(getContext(), surveytitle);
	}

	/**
	 * Set value of surveyTitle
	 * @param context
	 * @param surveytitle
	 */
	public final void setsurveyTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String surveytitle)
	{
		getMendixObject().setValue(context, MemberNames.surveyTitle.toString(), surveytitle);
	}

	/**
	 * @return value of surveyDescription
	 */
	public final java.lang.String getsurveyDescription()
	{
		return getsurveyDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of surveyDescription
	 */
	public final java.lang.String getsurveyDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.surveyDescription.toString());
	}

	/**
	 * Set value of surveyDescription
	 * @param surveydescription
	 */
	public final void setsurveyDescription(java.lang.String surveydescription)
	{
		setsurveyDescription(getContext(), surveydescription);
	}

	/**
	 * Set value of surveyDescription
	 * @param context
	 * @param surveydescription
	 */
	public final void setsurveyDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String surveydescription)
	{
		getMendixObject().setValue(context, MemberNames.surveyDescription.toString(), surveydescription);
	}

	/**
	 * @return value of survey_schema
	 */
	public final java.lang.String getsurvey_schema()
	{
		return getsurvey_schema(getContext());
	}

	/**
	 * @param context
	 * @return value of survey_schema
	 */
	public final java.lang.String getsurvey_schema(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.survey_schema.toString());
	}

	/**
	 * Set value of survey_schema
	 * @param survey_schema
	 */
	public final void setsurvey_schema(java.lang.String survey_schema)
	{
		setsurvey_schema(getContext(), survey_schema);
	}

	/**
	 * Set value of survey_schema
	 * @param context
	 * @param survey_schema
	 */
	public final void setsurvey_schema(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String survey_schema)
	{
		getMendixObject().setValue(context, MemberNames.survey_schema.toString(), survey_schema);
	}

	/**
	 * @return value of ui_schema
	 */
	public final java.lang.String getui_schema()
	{
		return getui_schema(getContext());
	}

	/**
	 * @param context
	 * @return value of ui_schema
	 */
	public final java.lang.String getui_schema(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ui_schema.toString());
	}

	/**
	 * Set value of ui_schema
	 * @param ui_schema
	 */
	public final void setui_schema(java.lang.String ui_schema)
	{
		setui_schema(getContext(), ui_schema);
	}

	/**
	 * Set value of ui_schema
	 * @param context
	 * @param ui_schema
	 */
	public final void setui_schema(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ui_schema)
	{
		getMendixObject().setValue(context, MemberNames.ui_schema.toString(), ui_schema);
	}

	/**
	 * @return value of init_data
	 */
	public final java.lang.String getinit_data()
	{
		return getinit_data(getContext());
	}

	/**
	 * @param context
	 * @return value of init_data
	 */
	public final java.lang.String getinit_data(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.init_data.toString());
	}

	/**
	 * Set value of init_data
	 * @param init_data
	 */
	public final void setinit_data(java.lang.String init_data)
	{
		setinit_data(getContext(), init_data);
	}

	/**
	 * Set value of init_data
	 * @param context
	 * @param init_data
	 */
	public final void setinit_data(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String init_data)
	{
		getMendixObject().setValue(context, MemberNames.init_data.toString(), init_data);
	}

	/**
	 * @return value of i18n_data
	 */
	public final java.lang.String geti18n_data()
	{
		return geti18n_data(getContext());
	}

	/**
	 * @param context
	 * @return value of i18n_data
	 */
	public final java.lang.String geti18n_data(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.i18n_data.toString());
	}

	/**
	 * Set value of i18n_data
	 * @param i18n_data
	 */
	public final void seti18n_data(java.lang.String i18n_data)
	{
		seti18n_data(getContext(), i18n_data);
	}

	/**
	 * Set value of i18n_data
	 * @param context
	 * @param i18n_data
	 */
	public final void seti18n_data(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String i18n_data)
	{
		getMendixObject().setValue(context, MemberNames.i18n_data.toString(), i18n_data);
	}

	/**
	 * @return value of response
	 */
	public final java.lang.String getresponse()
	{
		return getresponse(getContext());
	}

	/**
	 * @param context
	 * @return value of response
	 */
	public final java.lang.String getresponse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.response.toString());
	}

	/**
	 * Set value of response
	 * @param response
	 */
	public final void setresponse(java.lang.String response)
	{
		setresponse(getContext(), response);
	}

	/**
	 * Set value of response
	 * @param context
	 * @param response
	 */
	public final void setresponse(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String response)
	{
		getMendixObject().setValue(context, MemberNames.response.toString(), response);
	}

	/**
	 * @return value of language
	 */
	public final java.lang.String getlanguage()
	{
		return getlanguage(getContext());
	}

	/**
	 * @param context
	 * @return value of language
	 */
	public final java.lang.String getlanguage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.language.toString());
	}

	/**
	 * Set value of language
	 * @param language
	 */
	public final void setlanguage(java.lang.String language)
	{
		setlanguage(getContext(), language);
	}

	/**
	 * Set value of language
	 * @param context
	 * @param language
	 */
	public final void setlanguage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String language)
	{
		getMendixObject().setValue(context, MemberNames.language.toString(), language);
	}

	/**
	 * @return value of readonly
	 */
	public final java.lang.Boolean getreadonly()
	{
		return getreadonly(getContext());
	}

	/**
	 * @param context
	 * @return value of readonly
	 */
	public final java.lang.Boolean getreadonly(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.readonly.toString());
	}

	/**
	 * Set value of readonly
	 * @param readonly
	 */
	public final void setreadonly(java.lang.Boolean readonly)
	{
		setreadonly(getContext(), readonly);
	}

	/**
	 * Set value of readonly
	 * @param context
	 * @param readonly
	 */
	public final void setreadonly(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean readonly)
	{
		getMendixObject().setValue(context, MemberNames.readonly.toString(), readonly);
	}

	/**
	 * @return value of jsonStyle
	 */
	public final java.lang.String getjsonStyle()
	{
		return getjsonStyle(getContext());
	}

	/**
	 * @param context
	 * @return value of jsonStyle
	 */
	public final java.lang.String getjsonStyle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.jsonStyle.toString());
	}

	/**
	 * Set value of jsonStyle
	 * @param jsonstyle
	 */
	public final void setjsonStyle(java.lang.String jsonstyle)
	{
		setjsonStyle(getContext(), jsonstyle);
	}

	/**
	 * Set value of jsonStyle
	 * @param context
	 * @param jsonstyle
	 */
	public final void setjsonStyle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String jsonstyle)
	{
		getMendixObject().setValue(context, MemberNames.jsonStyle.toString(), jsonstyle);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return surveyMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Survey that = (myfirstmodule.proxies.Survey) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
